import unittest
from proteomics.test.db_testcase import DBTestCase
from proteomics import db
from proteomics.services.ingest import FastaIngestService
import tempfile
import os


class FastaIngestServiceTestCase(DBTestCase):
    def setUp(self):
        DBTestCase.setUp(self)
        hndl, self.fasta_file = tempfile.mkstemp(prefix="tst.fasta.")
        with open(self.fasta_file, 'wb') as fh:
            fh.write(self.get_mock_fasta())

    def test_ingest_fasta(self):
        ingest_service = FastaIngestService()
        actual = ingest_service.ingest(
            fasta_file=self.fasta_file,
            genome=None,
            session=db.session()
        )
        expected = {
            'new_proteins': 3,
            'unique_proteins': 3,
            'new_protein_instances': 4
        }
        self.assertEqual(actual, expected)

    def tearDown(self):
        DBTestCase.tearDown(self)
        os.remove(self.fasta_file)

    def get_mock_fasta(self):
        return """
>638957745 ZP_01083369 WH5701_03745 putative glutamate synthetase [Synechococcus sp. WH 5701]
MNLEEGKDYFYCACGRSSDQPFCDGSHEGSGFTPLAFVAERGGKALLCRC
KQTATPPYCDGTHTRVPADRVGTTFSVDADGEGDGTEEGDGNDADPEEPD
HHGMPEPRATAEEPNLELIHQLAEHGLDRMGAEGPVAAMGVPRSLLPLWD
DIQILTAQLARRPLAGDAAVGTELVIGPRARRPLRLEIPLLVSDMSFGAL
SEEAKQALATGAERAGTGICSGEGGMLPEEQAANHRYLYELAPAMFGYRE
EVLSQVQAFHFKAGQAAKTGTGSHLPGAKVTARIAEIRGIPEGQPSCSPA
VFSDLHSPADFRAFGDRVRELSGGIPVGMKLSAQHIEHDLDFALEAGVDY
LILDGRGGGTGGAPLLFRDHIAVPTIPALARARAHLDRSGVGGQVTLIVT
GGLRTPADCIKALALGADGVALANAAIQAIGCVGSRICHTNRCPAGVATQ
DPQLRRRLEVEHAALRLERFLRATVALMQVMARACGHDHLGRLRREDLAS
WHRDLAELAGIAWSGRSRCQLARSSRRSRPR

>638957746 ZP_01083370 WH5701_03750 ABC transporter for sugars, solute-binding protein [Synechococcus sp. WH 5701]
MGLRSTLRYAALALLLVGLIVSGGLRAQRQEPVIVTALMPAPFAEATAPI
VERFNRRHPGIELRVNRGPFETEAISDLAISSLLLGDSPYDLLLMDVTWT
PKYAAAGWLAPLEPLLGEDALAGVVPGAREGNRFDGHLWRIPLVADMGLL
YWRTDLMAAPPRTPDELMATAGALQRAGRVRWGYVWQGRQYEGLSCVFLE
VLRGFGGQWLSASADRVELGSPAGVAAASWLRQLIDLGITPRAVANFAEP
EALQSFEAGDAALMRNWPYAWAELQKPGSQVRGKVGVTTMVAAPGGSPAA
TQGSWGFSLVSQSPHPREAALVIAALTAPGVQKDLARRLGYTPTLSALFE
DPELVAANPVLPELRRALEATVLRPLSPLYAQLSDILQRQLSEVITGERE
PAEGMERAQRLSNQLLRASGVGASGVEARS

>638957747 ZP_01083371 WH5701_03755 ABC transporter for possibly for trehalose/maltose, membrane component [Synechococcus sp. WH 5701]
MTLLLTLPALLLLALVFAVPLLRYGWLSFHADSVITGLQPVPNGGANWLR
LIEDERFWQDTVQTLRFAGLSVALELLLGLALALLLHQSWRGRTAVRTIT
LLPWALPTAVMALGWRWIFNDPYGPINALVQALGLPALPFLSSPASTWLV
VVLADVWKTTPFVALLLLAGLQSIPTDLYEAFALEGGTSAQALRQITLPL
LLPYAFLAVLFRLAQALGVFDLVQILTGGGPAGSTETLALYSYLSAMRFL
DFGYSATVMLGMFVLLLGLTAALLLGRRWLAGGRS

>DUPLICATE_OF_638957745 ZP_01083369 WH5701_03745 putative glutamate synthetase [Synechococcus sp. WH 5701]
MNLEEGKDYFYCACGRSSDQPFCDGSHEGSGFTPLAFVAERGGKALLCRC
KQTATPPYCDGTHTRVPADRVGTTFSVDADGEGDGTEEGDGNDADPEEPD
HHGMPEPRATAEEPNLELIHQLAEHGLDRMGAEGPVAAMGVPRSLLPLWD
DIQILTAQLARRPLAGDAAVGTELVIGPRARRPLRLEIPLLVSDMSFGAL
SEEAKQALATGAERAGTGICSGEGGMLPEEQAANHRYLYELAPAMFGYRE
EVLSQVQAFHFKAGQAAKTGTGSHLPGAKVTARIAEIRGIPEGQPSCSPA
VFSDLHSPADFRAFGDRVRELSGGIPVGMKLSAQHIEHDLDFALEAGVDY
LILDGRGGGTGGAPLLFRDHIAVPTIPALARARAHLDRSGVGGQVTLIVT
GGLRTPADCIKALALGADGVALANAAIQAIGCVGSRICHTNRCPAGVATQ
DPQLRRRLEVEHAALRLERFLRATVALMQVMARACGHDHLGRLRREDLAS
WHRDLAELAGIAWSGRSRCQLARSSRRSRPR
"""

if __name__ == '__main__':
    unittest.main()
